###
POST http://localhost:8080/signup HTTP/1.1
content-type: application/json

{
    "username": "sample",
    "password": "asdfasdinfaiosdnfoas"
}

###
GET http://localhost:8080/signin HTTP/1.1

content-type: application/json
{
    "username": "sample",
    "password": "asdfasdinfaiosdnfoas"
}

###
POST http://localhost:8080/api/signout HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4MjI1MjM0MiwiZXhwIjoxNzgyMjU5NTQyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0In0.HIunixJNsucFv_FvlCUASGZWPVyJpQ-_b9VehW2HgZo

###
GET http://localhost:8080/api/dashboard HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4MjI1MjM0MiwiZXhwIjoxNzgyMjU5NTQyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0In0.HIunixJNsucFv_FvlCUASGZWPVyJpQ-_b9VehW2HgZo

###
GET http://localhost:8080/api/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4MjI1MjM0MiwiZXhwIjoxNzgyMjU5NTQyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0In0.HIunixJNsucFv_FvlCUASGZWPVyJpQ-_b9VehW2HgZo
